#!/bin/sh

if ! [ $(which xclip) ]; then
	echo "\n xclip no está instalado"
    echo " [!] Ejecuta: sudo apt install xclip"
elif [ -z $1 ]; then
    echo "Usage: ./extractports <nmap-scan>"
else

	ports="$(cat $1 | grep "^[0-9]" | awk '{print $1}' FS='/' | tr '\n' ',' | sed 's/.$//')"
	ip_address="$(cat $1 | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | sort -u | head -n 1)"

	echo "\n  [*] Extrayendo puertos...\n"

	echo "\t[+] Dirección IP: $ip_address"
	echo "\t[+] Puertos Abiertos: $ports\n"

	echo $ports | tr -d '\n' | xclip -sel clip
	echo "  [*] Puertos copiados a la Clipboard\n"

fi
